version: '3'

services:
  front:
    build: ./front
    container_name: front
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./front:/app
    working_dir: /app/capsule-collection
    env_file: ./front/.env
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "bun run dev"
